### ISSUE TITLE
Script doesn't load DIC images

### ISSUE THREAD

**Issue by moettl** [alemoro/sCaSpA#3]
Hi Ale,

When I load my data only the fluorescent image is displayed but not the DIC image. Both are labeled in the same exact way except that the  name of the DICs contains 'DIC' additionally. I have 4 elements in the name (220223_MultiHet-w3_well04_rec01 / 220223_MultiHet-w3-DIC_well04_rec01).

Also, when I click 'show movie', it gives me this error message:

Error using fopen
First input must be a file name or a file identifier.

Error in loadTiff (line 6)
imgStackID = fopen(imgFile, 'r');

Error in sCaSpA/ShowTimelapseChanged (line 572)
                    imgStack = loadTiff(app, imgIdx, 1);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating StateButton PrivateValueChangedFcn.

It's both in the newest version that you just updated and in a previous one.

Best,
Miriam

**Comment by alemoro** [comment]
What is the name that you use for the "Still Condition"? with the example that you sent me you should use "MultiHet-w3-DIC" as the still condition.

For the show movie, I don't have an answer yet. I will look at it in the next couple of days
